services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  backend:
    build: ./backend
    container_name: course-backend
    env_file: .env
    environment:
      SQLITE_PATH: /app/courses/database/courses.sqlite
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: "8000"
      MODEL_URL: http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - sqlite-data:/app/courses/database
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build: ./frontend
    container_name: course-frontend
    ports: ["8080:8080"]
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:8080').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 10s
      timeout: 3s
      retries: 10

  proxy:
    image: caddy:2-alpine
    container_name: course-proxy
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - "80:80"
      # - "443:443"   # enable if you add TLS
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

volumes:
  ollama: {}
  sqlite-data:
  caddy-data:
  caddy-config:

