services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB} -q"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  backend:
    build: ./backend
    container_name: autodactyl-backend
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: "8000"
      MODEL_URL: http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build: ./frontend
    container_name: autodactyl-frontend
    ports: ["8080:8080"]
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:8080').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 10s
      timeout: 3s
      retries: 10

  proxy:
    image: caddy:2-alpine
    container_name: autodactyl-proxy
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - "80:80"
      # - "443:443"   # enable if add TLS
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

volumes:
  ollama:
  pgdata:
  caddy-data:
  caddy-config:

